version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: cards-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cards_db
      MYSQL_USER: cards_user
      MYSQL_PASSWORD: cards_password

    command: --default-authentication-plugin=mysql_native_password

    ports:
      - "3307:3306"

    volumes:
      - cards_db_data:/var/lib/mysql
      - ./src/main/resources/db:/docker-entrypoint-initdb.d

    networks:
      - cards-net

volumes:
  cards_db_data:
    name: cards_mysql_data

networks:
  cards-net:
    driver: bridge